#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
fi

# Expose custom_components to Home Assistant without symlinks.
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

hass --config "${PWD}/config" --debug
